languageCode = 'en-us'
title = "Maarten's notes"

baseURL = 'https://maarteng18.github.io/notes/'
# fix for subdir baseurl, see https://discourse.gohugo.io/t/issue-when-baseurl-have-subdirectory/4088/7
RelativeURLs=true
CanonifyURLs=true

theme = "hugo-theme-kul"
publishDir = "docs"
enableEmoji = true
enableRobotsTXT = true
pygmentsCodefences = true

# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true

[markup]
	defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    unsafe= true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4
    style = "monokailight"

[taxonomies]
    tag = "tags"

[params]
    disableComments = true
    disableInlineCopyToClipBoard = true
    ordersectionsby = "weight"

# see https://learn.netlify.com/en/basics/configuration/
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Author]
	name = "Maarten Gielkens"
	email = "maartengielkens2000@gmail.com"